...

diff --git a/utils/org/img_replacer b/utils/org/img_replacer
--- a/utils/org/img_replacer
+++ b/utils/org/img_replacer
@@ -15,36 +15,40 @@ if [[ -f $1 ]]; then
     IMGC=$(wc -l $T1 | awk '{print $1}')
     echo "count:$IMGC"
 
-    for I in $(seq 1 $IMGC); do
-        #((LPO=L+1))
-        F=$(tail -n +$I $T1 | head -1 | gsed -E 's/.*<img src="([^"]+)".*/\1/g')
+    if [[ $IMGC -gt 0 ]]; then
 
-        openssl base64 -in $F -out $TPRE$I.withnewlines
-        cat $TPRE$I.withnewlines | tr -d '\n' | tr -d '\r' >$TPRE$I
+        for I in $(seq 1 $IMGC); do
+            #((LPO=L+1))
+            F=$(tail -n +$I $T1 | head -1 | gsed -E 's/.*<img src="([^"]+)".*/\1/g')
+
+            openssl base64 -in $F -out $TPRE$I.withnewlines
+            cat $TPRE$I.withnewlines | tr -d '\n' | tr -d '\r' >$TPRE$I
 
 
-        MT=""
+            MT=""
 
-        if [[ "$F" == *".png" ]]; then
-            MT="image/png"
-        fi
+            if [[ "$F" == *".png" ]]; then
+                MT="image/png"
+            fi
 
-        if [[ "$F" == *".jpg" ]]; then
-            MT="image/jpeg"
-        fi
+            if [[ "$F" == *".jpg" ]]; then
+                MT="image/jpeg"
+            fi
 
-        if [[ -z "$MT" ]]; then
-            echo "error unknown file type for $F"
-            exit 1
-        fi
+            if [[ -z "$MT" ]]; then
+                echo "error unknown file type for $F"
+                exit 1
+            fi
 
-        echo -n "data:$MT;base64,">$TPRE$I.data
+            echo -n "data:$MT;base64,">$TPRE$I.data
 
-        cat $TPRE$I >> $TPRE$I.data
+            cat $TPRE$I >> $TPRE$I.data
 
-        gsed -Ei "s|(.*<img src=\")$F(\".*)|\\1`cat $TPRE$I.data`\\2|g" $O
-        echo "$I: $F"
-    done
+            gsed -Ei "s|(.*<img src=\")$F(\".*)|\\1`cat $TPRE$I.data`\\2|g" $O
+            echo "$I: $F"
+        done
+
+    fi
 
     cat $O > "$1"
     rm -f $O
